#!/bin/sh 

set -xe 

# mkdir tmp

purs-nix bundle
# mv index.js tmp/

sed 's/script src="[a-zA-Z\.\/]*"/script src=".\/index.js"/g' static/index.html > index.html
parcel build -d dist --public-url ./ --experimental-scope-hoisting index.html

rm index.js
rm index.html

# closure-compiler --compilation_level ADVANCED_OPTIMIZATIONS --js tmp/*.js --js_output_file tmp/index.prod.minified.js

# rm -r tmp
